import FWCore.ParameterSet.Config as cms

globalCorD0 = cms.EDProducer(
    'ResidualGlobalCorrectionMakerTwoTrackKPiG4e',
    src=cms.InputTag('ALCARECOTkAlDstToD0Pi'),
    fitFromGenParms=cms.bool(False),
    fitFromSimParms=cms.bool(False),
    fillTrackTree=cms.bool(True),
    fillGrads=cms.bool(False),
    fillJac=cms.bool(False),
    fillRunTree=cms.bool(False),
    doGen=cms.bool(False),
    genParticles=cms.InputTag('genParticles'),
    pileupInfo=cms.InputTag('addPileupInfo'),
    doSim=cms.bool(False),
    requireGen=cms.bool(False),
    doMuons=cms.bool(False),
    muons=cms.InputTag('muons'),
    doMuonAssoc=cms.bool(False),
    doTrigger=cms.bool(False),
    triggers=cms.vstring(),
    doL1Trigger=cms.bool(False),
    l1Results=cms.InputTag('gtDigis', '', 'RECO'),
    l1Triggers=cms.vstring(),
    doRes=cms.bool(False),
    useIdealGeometry=cms.bool(True),
    bsConstraint=cms.bool(False),
    applyHitQuality=cms.bool(True),
    doVtxConstraint=cms.bool(False),
    doMassConstraint=cms.bool(False),
    massConstraint=cms.double(1.86483),
    massConstraintWidth=cms.double(1e-5),
    kaonMass=cms.double(0.493677),
    pionMass=cms.double(0.139570),
    kaonMassErr=cms.double(1e-6),
    pionMassErr=cms.double(1e-6),
    minPairMass=cms.double(1.70),
    maxPairMass=cms.double(2.00),
    respectTrackOrder=cms.bool(False),
    corFiles=cms.vstring(),
    MagneticFieldLabel=cms.string(''),
    outprefix=cms.untracked.string('globalcor_d0')
)
